name: SSH Checkout Workflow

env:
  FOLDER_NAME: FunkyGameBot

on:
  workflow_dispatch:
  push:
    branches:
      - server

jobs:
  basic_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ls
            #cd $FOLDER_NAME
